application:
    appName: srs

spring:
    application:
        name: srsservice
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/srs
        username: srs
        password: srs
        hikari:
            poolName: Hikari
<<<<<<< HEAD
<<<<<<< HEAD
            auto_commit: false
=======
            auto-commit: false
>>>>>>> 8faed6e89a8087475c1ef5e3e30fddb8ea58e219
=======
            auto-commit: false

>>>>>>> f99a033b0674891d3110d1dcf0a43e9c70c7532e
    jackson:
        date-format: yyyy-MM-dd
        deserialization:
            fail-on-unknown-properties: false
<<<<<<< HEAD
=======

>>>>>>> f99a033b0674891d3110d1dcf0a43e9c70c7532e
    jpa:
#        database-platform: io.github.jhipster.domain.util.FixedPostgreSQL95Dialect
        database: POSTGRESQL
        show-sql: true
        open-in-view: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    liquibase:
        change-log: classpath:/db/master.xml
#        drop-first: true
server:
    port: 8080
